version: '3'
services:
  app:
    build:
      context: .
      args:
       TAG: ${TAG}
    environment:
     - TEST_VARIABLE=${TEST_VARIABLE}
     - TAG=${TAG}
    tty: true    
volumes:
  media: null